#include <farversion.hpp>

#define COMPANYNAME 0
#define PLUGIN_DESC L"FARDroid FAR Plugin"
#define PLUGIN_NAME L"FARDroid"
#define PLUGIN_FILENAME L"fardroid.dll"
#define PLUGIN_COPYRIGHT_INITIAL L"dimfish 2016"
#define PLUGIN_COPYRIGHT_CURRENT L", Vladimir Kubyshev 2010"
#define PLUGIN_AUTHOR PLUGIN_COPYRIGHT_INITIAL PLUGIN_COPYRIGHT_CURRENT
#define PLUGIN_MAJOR 2026
#define PLUGIN_MINOR 04
#define PLUGIN_REVISION 0
#define PLUGIN_BUILD 23
#define PLUGIN_VERSION MAKEFARVERSION(PLUGIN_MAJOR,PLUGIN_MINOR,PLUGIN_REVISION,PLUGIN_BUILD,VS_RELEASE)
